use master;
drop DATABASE LerngruppenKoordinatorDB;

CREATE DATABASE LerngruppenKoordinatorDB;
USE LerngruppenKoordinatorDB;

CREATE TABLE BENUTZER (
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR(100) NOT NULL,
	ADRESSE VARCHAR(255),
	PLZ VARCHAR(255),
	STUDIENGANG VARCHAR(100),
	FACHSEMESTER INT
);

CREATE TABLE LERNGRUPPE ( 
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR(100) NOT NULL,
	FACH VARCHAR(255),
	ADRESSE VARCHAR(250),
	PLZ VARCHAR(10)
);

CREATE TABLE Terminkalender (
	BenutzerID INT,
	LERNGRUPPENID INT,
	TERMIN DATETIME DEFAULT GETDATE(),
	PRIMARY KEY (BENUTZERID, LERNGRUPPENID),
	FOREIGN KEY (BENUTZERID) REFERENCES BENUTZER(ID),
	FOREIGN KEY (LERNGRUPPENID) REFERENCES LERNGRUPPE(ID),
	);